"""
All Pokémon names Gen 1-6 (1-721) in English and German.
Used by the identifier for OCR fuzzy matching.
"""

# (English, German) — index = Pokédex number - 1
POKEMON_ALL = [
    # Gen 1 (1-151)
    ("Bulbasaur", "Bisasam"), ("Ivysaur", "Bisaknosp"), ("Venusaur", "Bisaflor"),
    ("Charmander", "Glumanda"), ("Charmeleon", "Glutexo"), ("Charizard", "Glurak"),
    ("Squirtle", "Schiggy"), ("Wartortle", "Schillok"), ("Blastoise", "Turtok"),
    ("Caterpie", "Raupy"), ("Metapod", "Safcon"), ("Butterfree", "Smettbo"),
    ("Weedle", "Hornliu"), ("Kakuna", "Kokuna"), ("Beedrill", "Bibor"),
    ("Pidgey", "Taubsi"), ("Pidgeotto", "Tauboga"), ("Pidgeot", "Tauboss"),
    ("Rattata", "Rattfratz"), ("Raticate", "Rattikarl"),
    ("Spearow", "Habitak"), ("Fearow", "Ibitak"),
    ("Ekans", "Rettan"), ("Arbok", "Arbok"),
    ("Pikachu", "Pikachu"), ("Raichu", "Raichu"),
    ("Sandshrew", "Sandan"), ("Sandslash", "Sandamer"),
    ("Nidoran", "Nidoran"), ("Nidorina", "Nidorina"),
    ("Nidoqueen", "Nidoqueen"), ("Nidorino", "Nidorino"), ("Nidoking", "Nidoking"),
    ("Clefairy", "Piepi"), ("Clefable", "Pixi"),
    ("Vulpix", "Vulpix"), ("Ninetales", "Vulnona"),
    ("Jigglypuff", "Pummeluff"), ("Wigglytuff", "Knuddeluff"),
    ("Zubat", "Zubat"), ("Golbat", "Golbat"),
    ("Oddish", "Myrapla"), ("Gloom", "Duflor"), ("Vileplume", "Giflor"),
    ("Paras", "Paras"), ("Parasect", "Parasek"),
    ("Venonat", "Bluzuk"), ("Venomoth", "Omot"),
    ("Diglett", "Digda"), ("Dugtrio", "Digdri"),
    ("Meowth", "Mauzi"), ("Persian", "Snobilikat"),
    ("Psyduck", "Enton"), ("Golduck", "Entoron"),
    ("Mankey", "Menki"), ("Primeape", "Rasaff"),
    ("Growlithe", "Fukano"), ("Arcanine", "Arkani"),
    ("Poliwag", "Quapsel"), ("Poliwhirl", "Quaputzi"), ("Poliwrath", "Quappo"),
    ("Abra", "Abra"), ("Kadabra", "Kadabra"), ("Alakazam", "Simsala"),
    ("Machop", "Machollo"), ("Machoke", "Maschock"), ("Machamp", "Machomei"),
    ("Bellsprout", "Knofensa"), ("Weepinbell", "Ultrigaria"), ("Victreebel", "Sarzenia"),
    ("Tentacool", "Tentacha"), ("Tentacruel", "Tentoxa"),
    ("Geodude", "Kleinstein"), ("Graveler", "Georok"), ("Golem", "Geowaz"),
    ("Ponyta", "Ponita"), ("Rapidash", "Gallopa"),
    ("Slowpoke", "Flegmon"), ("Slowbro", "Lahmus"),
    ("Magnemite", "Magnetilo"), ("Magneton", "Magneton"),
    ("Farfetchd", "Porenta"), ("Doduo", "Dodu"), ("Dodrio", "Dodri"),
    ("Seel", "Jurob"), ("Dewgong", "Jugong"),
    ("Grimer", "Sleima"), ("Muk", "Sleimok"),
    ("Shellder", "Muschas"), ("Cloyster", "Austos"),
    ("Gastly", "Nebulak"), ("Haunter", "Alpollo"), ("Gengar", "Gengar"),
    ("Onix", "Onix"), ("Drowzee", "Traumato"), ("Hypno", "Hypno"),
    ("Krabby", "Krabby"), ("Kingler", "Kingler"),
    ("Voltorb", "Voltobal"), ("Electrode", "Lektrobal"),
    ("Exeggcute", "Owei"), ("Exeggutor", "Kokowei"),
    ("Cubone", "Tragosso"), ("Marowak", "Knogga"),
    ("Hitmonlee", "Kicklee"), ("Hitmonchan", "Nockchan"),
    ("Lickitung", "Schlurp"), ("Koffing", "Smogon"), ("Weezing", "Smogmog"),
    ("Rhyhorn", "Rihorn"), ("Rhydon", "Rizeros"),
    ("Chansey", "Chaneira"), ("Tangela", "Tangela"),
    ("Kangaskhan", "Kangama"), ("Horsea", "Seeper"), ("Seadra", "Seemon"),
    ("Goldeen", "Goldini"), ("Seaking", "Golking"),
    ("Staryu", "Sterndu"), ("Starmie", "Starmie"),
    ("Mr. Mime", "Pantimos"), ("Scyther", "Sichlor"),
    ("Jynx", "Rossana"), ("Electabuzz", "Elektek"), ("Magmar", "Magmar"),
    ("Pinsir", "Pinsir"), ("Tauros", "Tauros"),
    ("Magikarp", "Karpador"), ("Gyarados", "Garados"),
    ("Lapras", "Lapras"), ("Ditto", "Ditto"),
    ("Eevee", "Evoli"), ("Vaporeon", "Aquana"), ("Jolteon", "Blitza"), ("Flareon", "Flamara"),
    ("Porygon", "Porygon"), ("Omanyte", "Amonitas"), ("Omastar", "Amoroso"),
    ("Kabuto", "Kabuto"), ("Kabutops", "Kabutops"),
    ("Aerodactyl", "Aerodactyl"), ("Snorlax", "Relaxo"),
    ("Articuno", "Arktos"), ("Zapdos", "Zapdos"), ("Moltres", "Lavados"),
    ("Dratini", "Dratini"), ("Dragonair", "Dragonir"), ("Dragonite", "Dragoran"),
    ("Mewtwo", "Mewtu"), ("Mew", "Mew"),
    # Gen 2 (152-251)
    ("Chikorita", "Endivie"), ("Bayleef", "Lorblatt"), ("Meganium", "Meganie"),
    ("Cyndaquil", "Feurigel"), ("Quilava", "Igelavar"), ("Typhlosion", "Tornupto"),
    ("Totodile", "Karnimani"), ("Croconaw", "Tyracroc"), ("Feraligatr", "Impergator"),
    ("Sentret", "Wiesor"), ("Furret", "Wiesenior"),
    ("Hoothoot", "Hoothoot"), ("Noctowl", "Noctuh"),
    ("Ledyba", "Ledyba"), ("Ledian", "Ledian"),
    ("Spinarak", "Webarak"), ("Ariados", "Ariados"),
    ("Crobat", "Iksbat"), ("Chinchou", "Lampi"), ("Lanturn", "Lanturn"),
    ("Pichu", "Pichu"), ("Cleffa", "Pii"), ("Igglybuff", "Fluffeluff"),
    ("Togepi", "Togepi"), ("Togetic", "Togetic"),
    ("Natu", "Natu"), ("Xatu", "Xatu"),
    ("Mareep", "Voltilamm"), ("Flaaffy", "Waaty"), ("Ampharos", "Ampharos"),
    ("Bellossom", "Blubella"), ("Marill", "Marill"), ("Azumarill", "Azumarill"),
    ("Sudowoodo", "Mogelbaum"), ("Politoed", "Quaxo"),
    ("Hoppip", "Hoppspross"), ("Skiploom", "Hubelupf"), ("Jumpluff", "Papungha"),
    ("Aipom", "Griffel"), ("Sunkern", "Sonnkern"), ("Sunflora", "Sonnflora"),
    ("Yanma", "Yanma"), ("Wooper", "Felino"), ("Quagsire", "Morlord"),
    ("Espeon", "Psiana"), ("Umbreon", "Nachtara"),
    ("Murkrow", "Kramurx"), ("Slowking", "Laschoking"),
    ("Misdreavus", "Traunfugil"), ("Unown", "Icognito"),
    ("Wobbuffet", "Woingenau"), ("Girafarig", "Girafarig"),
    ("Pineco", "Tannza"), ("Forretress", "Forstellka"),
    ("Dunsparce", "Dummisel"), ("Gligar", "Skorgla"),
    ("Steelix", "Stahlos"), ("Snubbull", "Snubbull"), ("Granbull", "Granbull"),
    ("Qwilfish", "Baldorfish"), ("Scizor", "Scherox"),
    ("Shuckle", "Pottrott"), ("Heracross", "Skaraborn"),
    ("Sneasel", "Sniebel"), ("Teddiursa", "Teddiursa"), ("Ursaring", "Ursaring"),
    ("Slugma", "Schneckmag"), ("Magcargo", "Magcargo"),
    ("Swinub", "Quiekel"), ("Piloswine", "Keifel"),
    ("Corsola", "Corasonn"), ("Remoraid", "Remoraid"), ("Octillery", "Octillery"),
    ("Delibird", "Botogel"), ("Mantine", "Mantax"),
    ("Skarmory", "Panzaeron"), ("Houndour", "Hunduster"), ("Houndoom", "Hundemon"),
    ("Kingdra", "Seedraking"), ("Phanpy", "Phanpy"), ("Donphan", "Donphan"),
    ("Porygon2", "Porygon2"), ("Stantler", "Damhirplex"),
    ("Smeargle", "Farbeagle"), ("Tyrogue", "Rabauz"),
    ("Hitmontop", "Kapoera"), ("Smoochum", "Kussilla"),
    ("Elekid", "Elekid"), ("Magby", "Magby"), ("Miltank", "Miltank"),
    ("Blissey", "Heiteira"), ("Raikou", "Raikou"),
    ("Entei", "Entei"), ("Suicune", "Suicune"),
    ("Larvitar", "Larvitar"), ("Pupitar", "Pupitar"), ("Tyranitar", "Despotar"),
    ("Lugia", "Lugia"), ("Ho-Oh", "Ho-Oh"), ("Celebi", "Celebi"),
    # Gen 3 (252-386)
    ("Treecko", "Geckarbor"), ("Grovyle", "Reptain"), ("Sceptile", "Gewaldro"),
    ("Torchic", "Flemmli"), ("Combusken", "Jungglut"), ("Blaziken", "Lohgock"),
    ("Mudkip", "Hydropi"), ("Marshtomp", "Moorabbel"), ("Swampert", "Sumpex"),
    ("Poochyena", "Fiffyen"), ("Mightyena", "Magnayen"),
    ("Zigzagoon", "Zigzachs"), ("Linoone", "Geradaks"),
    ("Wurmple", "Waumpel"), ("Silcoon", "Schaloko"), ("Beautifly", "Papinella"),
    ("Cascoon", "Panekon"), ("Dustox", "Pudox"),
    ("Lotad", "Loturzel"), ("Lombre", "Lombrero"), ("Ludicolo", "Kappalores"),
    ("Seedot", "Samurzel"), ("Nuzleaf", "Blanas"), ("Shiftry", "Tengulist"),
    ("Taillow", "Schwalbini"), ("Swellow", "Schwalboss"),
    ("Wingull", "Wingull"), ("Pelipper", "Pelipper"),
    ("Ralts", "Trasla"), ("Kirlia", "Kirlia"), ("Gardevoir", "Guardevoir"),
    ("Surskit", "Gehweiher"), ("Masquerain", "Maskeregen"),
    ("Shroomish", "Knilz"), ("Breloom", "Kapilz"),
    ("Slakoth", "Bummelz"), ("Vigoroth", "Muntier"), ("Slaking", "Letarking"),
    ("Nincada", "Nincada"), ("Ninjask", "Ninjask"), ("Shedinja", "Ninjatom"),
    ("Whismur", "Flurmel"), ("Loudred", "Krakeelo"), ("Exploud", "Krawumms"),
    ("Makuhita", "Makuhita"), ("Hariyama", "Hariyama"),
    ("Azurill", "Azurill"), ("Nosepass", "Nasgnet"),
    ("Skitty", "Eneco"), ("Delcatty", "Enekoro"),
    ("Sableye", "Zobiris"), ("Mawile", "Flunkifer"),
    ("Aron", "Stollunior"), ("Lairon", "Stollrak"), ("Aggron", "Stolloss"),
    ("Meditite", "Meditie"), ("Medicham", "Medicham"),
    ("Electrike", "Frizelbliz"), ("Manectric", "Voltenso"),
    ("Plusle", "Plusle"), ("Minun", "Minun"),
    ("Volbeat", "Volbeat"), ("Illumise", "Illumise"),
    ("Roselia", "Roselia"), ("Gulpin", "Schluppuck"), ("Swalot", "Schlukwech"),
    ("Carvanha", "Kanivanha"), ("Sharpedo", "Tohaido"),
    ("Wailmer", "Wailmer"), ("Wailord", "Wailord"),
    ("Numel", "Camaub"), ("Camerupt", "Camerupt"),
    ("Torkoal", "Qurtel"), ("Spoink", "Spoink"), ("Grumpig", "Groink"),
    ("Spinda", "Pandir"), ("Trapinch", "Knacklion"),
    ("Vibrava", "Vibrava"), ("Flygon", "Libelldra"),
    ("Cacnea", "Tuska"), ("Cacturne", "Noktuska"),
    ("Swablu", "Wablu"), ("Altaria", "Altaria"),
    ("Zangoose", "Sengo"), ("Seviper", "Vipitis"),
    ("Lunatone", "Lunastein"), ("Solrock", "Sonnfel"),
    ("Barboach", "Schmerbe"), ("Whiscash", "Welsar"),
    ("Corphish", "Krebscorps"), ("Crawdaunt", "Krebutack"),
    ("Baltoy", "Puppance"), ("Claydol", "Lepumentas"),
    ("Lileep", "Liliep"), ("Cradily", "Wielie"),
    ("Anorith", "Anorith"), ("Armaldo", "Armaldo"),
    ("Feebas", "Barschwa"), ("Milotic", "Milotic"),
    ("Castform", "Formeo"), ("Kecleon", "Kecleon"),
    ("Shuppet", "Shuppet"), ("Banette", "Banette"),
    ("Duskull", "Zwirrlicht"), ("Dusclops", "Zwirrklop"),
    ("Tropius", "Tropius"), ("Chimecho", "Palimpalim"),
    ("Absol", "Absol"), ("Wynaut", "Isso"),
    ("Snorunt", "Schneppke"), ("Glalie", "Firnontor"),
    ("Spheal", "Seemops"), ("Sealeo", "Seejong"), ("Walrein", "Walraisa"),
    ("Clamperl", "Perlu"), ("Huntail", "Aalabyss"), ("Gorebyss", "Saganabyss"),
    ("Relicanth", "Relicanth"), ("Luvdisc", "Liebiskus"),
    ("Bagon", "Kindwurm"), ("Shelgon", "Draschel"), ("Salamence", "Brutalanda"),
    ("Beldum", "Tanhel"), ("Metang", "Metang"), ("Metagross", "Metagross"),
    ("Regirock", "Regirock"), ("Regice", "Regice"), ("Registeel", "Registeel"),
    ("Latias", "Latias"), ("Latios", "Latios"),
    ("Kyogre", "Kyogre"), ("Groudon", "Groudon"), ("Rayquaza", "Rayquaza"),
    ("Jirachi", "Jirachi"), ("Deoxys", "Deoxys"),
    # Gen 4 (387-493)
    ("Turtwig", "Chelast"), ("Grotle", "Chelcarain"), ("Torterra", "Chelterrar"),
    ("Chimchar", "Panflam"), ("Monferno", "Panpyro"), ("Infernape", "Panferno"),
    ("Piplup", "Plinfa"), ("Prinplup", "Pliprin"), ("Empoleon", "Impoleon"),
    ("Starly", "Staralili"), ("Staravia", "Staravia"), ("Staraptor", "Staraptor"),
    ("Bidoof", "Bidiza"), ("Bibarel", "Bidifas"),
    ("Kricketot", "Zirpurze"), ("Kricketune", "Zirpeise"),
    ("Shinx", "Sheinux"), ("Luxio", "Luxio"), ("Luxray", "Luxtra"),
    ("Budew", "Knospi"), ("Roserade", "Roserade"),
    ("Cranidos", "Koknodon"), ("Rampardos", "Rameidon"),
    ("Shieldon", "Schilterus"), ("Bastiodon", "Bollterus"),
    ("Burmy", "Burmy"), ("Wormadam", "Burmadame"), ("Mothim", "Moterpel"),
    ("Combee", "Wadribie"), ("Vespiquen", "Honweisel"),
    ("Pachirisu", "Pachirisu"), ("Buizel", "Bamelin"), ("Floatzel", "Bojelin"),
    ("Cherubi", "Kikugi"), ("Cherrim", "Kinoso"),
    ("Shellos", "Schalellos"), ("Gastrodon", "Gastrodon"),
    ("Ambipom", "Ambidiffel"), ("Drifloon", "Driftlon"), ("Drifblim", "Drifzepeli"),
    ("Buneary", "Haspiror"), ("Lopunny", "Schlapor"),
    ("Mismagius", "Traunmagil"), ("Honchkrow", "Kramshef"),
    ("Glameow", "Charmian"), ("Purugly", "Shnurgarst"),
    ("Chingling", "Klingplim"), ("Stunky", "Skunkapuh"), ("Skuntank", "Skuntank"),
    ("Bronzor", "Bronzel"), ("Bronzong", "Bronzong"),
    ("Bonsly", "Mobai"), ("Mime Jr.", "Pantimimi"),
    ("Happiny", "Wonneira"), ("Chatot", "Plaudagei"),
    ("Spiritomb", "Kryppuk"), ("Gible", "Kaumalat"),
    ("Gabite", "Knarksel"), ("Garchomp", "Knakrack"),
    ("Munchlax", "Mampfaxo"), ("Riolu", "Riolu"), ("Lucario", "Lucario"),
    ("Hippopotas", "Hippopotas"), ("Hippowdon", "Hippoterus"),
    ("Skorupi", "Pionskora"), ("Drapion", "Piondragi"),
    ("Croagunk", "Glibunkel"), ("Toxicroak", "Toxiquak"),
    ("Carnivine", "Venuflibis"), ("Finneon", "Finneon"), ("Lumineon", "Lumineon"),
    ("Mantyke", "Mantirps"), ("Snover", "Shnebedeck"), ("Abomasnow", "Rexblisar"),
    ("Weavile", "Snibunna"), ("Magnezone", "Magnezone"),
    ("Lickilicky", "Schlurplek"), ("Rhyperior", "Rihornior"),
    ("Tangrowth", "Tangoloss"), ("Electivire", "Elevoltek"),
    ("Magmortar", "Magbrant"), ("Togekiss", "Togekiss"),
    ("Yanmega", "Yanmega"), ("Leafeon", "Folipurba"), ("Glaceon", "Glaziola"),
    ("Gliscor", "Skorgro"), ("Mamoswine", "Mamutel"),
    ("Porygon-Z", "Porygon-Z"), ("Gallade", "Galagladi"),
    ("Probopass", "Voluminas"), ("Dusknoir", "Zwirrfinst"),
    ("Froslass", "Frosdedje"), ("Rotom", "Rotom"),
    ("Uxie", "Selfe"), ("Mesprit", "Vesprit"), ("Azelf", "Tobutz"),
    ("Dialga", "Dialga"), ("Palkia", "Palkia"),
    ("Heatran", "Heatran"), ("Regigigas", "Regigigas"),
    ("Giratina", "Giratina"), ("Cresselia", "Cresselia"),
    ("Phione", "Phione"), ("Manaphy", "Manaphy"),
    ("Darkrai", "Darkrai"), ("Shaymin", "Shaymin"), ("Arceus", "Arceus"),
    # Gen 5 (494-649)
    ("Victini", "Victini"),
    ("Snivy", "Serpifeu"), ("Servine", "Efoserp"), ("Serperior", "Serpiroyal"),
    ("Tepig", "Floink"), ("Pignite", "Ferkokel"), ("Emboar", "Flambirex"),
    ("Oshawott", "Ottaro"), ("Dewott", "Zwottronin"), ("Samurott", "Admurai"),
    ("Patrat", "Nagelotz"), ("Watchog", "Kukmarda"),
    ("Lillipup", "Yorkleff"), ("Herdier", "Terribark"), ("Stoutland", "Bissbark"),
    ("Purrloin", "Felilou"), ("Liepard", "Kleoparda"),
    ("Pansage", "Vegimak"), ("Simisage", "Vegichita"),
    ("Pansear", "Grillmak"), ("Simisear", "Grillchita"),
    ("Panpour", "Sodamak"), ("Simipour", "Sodachita"),
    ("Munna", "Somniam"), ("Musharna", "Somnivora"),
    ("Pidove", "Dusselgurr"), ("Tranquill", "Navitaub"), ("Unfezant", "Fasasnob"),
    ("Blitzle", "Elezeba"), ("Zebstrika", "Zebritz"),
    ("Roggenrola", "Kiesling"), ("Boldore", "Sedimantur"), ("Gigalith", "Brockoloss"),
    ("Woobat", "Fleknoil"), ("Swoobat", "Fletiamo"),
    ("Drilbur", "Rotomurf"), ("Excadrill", "Stalobor"),
    ("Audino", "Ohrdoch"), ("Timburr", "Praktibalk"),
    ("Gurdurr", "Strepoli"), ("Conkeldurr", "Meistagrif"),
    ("Tympole", "Schallquap"), ("Palpitoad", "Mebrana"), ("Seismitoad", "Branawarz"),
    ("Throh", "Jiutesto"), ("Sawk", "Karadonis"),
    ("Sewaddle", "Strawickl"), ("Swadloon", "Folikon"), ("Leavanny", "Matrifol"),
    ("Venipede", "Toxiped"), ("Whirlipede", "Rollum"), ("Scolipede", "Cerapendra"),
    ("Cottonee", "Waumboll"), ("Whimsicott", "Elfun"),
    ("Petilil", "Lilminip"), ("Lilligant", "Dressella"),
    ("Basculin", "Barschuft"), ("Sandile", "Ganovil"),
    ("Krokorok", "Rokkaiman"), ("Krookodile", "Rabigator"),
    ("Darumaka", "Flampion"), ("Darmanitan", "Flampivian"),
    ("Maractus", "Maracamba"), ("Dwebble", "Lithomith"), ("Crustle", "Castellith"),
    ("Scraggy", "Zurrokex"), ("Scrafty", "Irokex"),
    ("Sigilyph", "Symvolara"), ("Yamask", "Makabaja"), ("Cofagrigus", "Echnatoll"),
    ("Tirtouga", "Galapaflos"), ("Carracosta", "Karippas"),
    ("Archen", "Flapteryx"), ("Archeops", "Aeropteryx"),
    ("Trubbish", "Unratutox"), ("Garbodor", "Deponitox"),
    ("Zorua", "Zorua"), ("Zoroark", "Zoroark"),
    ("Minccino", "Picochilla"), ("Cinccino", "Chillabell"),
    ("Gothita", "Mollimorba"), ("Gothorita", "Hypnomorba"), ("Gothitelle", "Morbitesse"),
    ("Solosis", "Monozyto"), ("Duosion", "Mitodos"), ("Reuniclus", "Zytomega"),
    ("Ducklett", "Piccolente"), ("Swanna", "Swaroness"),
    ("Vanillite", "Gelatini"), ("Vanillish", "Gelatroppo"), ("Vanilluxe", "Gelatwino"),
    ("Deerling", "Sesokitz"), ("Sawsbuck", "Kronjuwild"),
    ("Emolga", "Emolga"), ("Karrablast", "Laukaps"), ("Escavalier", "Cavalanzas"),
    ("Foongus", "Tarnpignon"), ("Amoonguss", "Hutsassa"),
    ("Frillish", "Quabbel"), ("Jellicent", "Apoquallyp"),
    ("Alomomola", "Mamolida"), ("Joltik", "Wattzapf"), ("Galvantula", "Voltula"),
    ("Ferroseed", "Kastadur"), ("Ferrothorn", "Tentantel"),
    ("Klink", "Klikk"), ("Klang", "Kliklak"), ("Klinklang", "Klikdiklak"),
    ("Tynamo", "Zapplardin"), ("Eelektrik", "Zapplalek"), ("Eelektross", "Zapplarang"),
    ("Elgyem", "Pygraulon"), ("Beheeyem", "Megalon"),
    ("Litwick", "Lichtel"), ("Lampent", "Laternecto"), ("Chandelure", "Skelabra"),
    ("Axew", "Milza"), ("Fraxure", "Shardrago"), ("Haxorus", "Maxax"),
    ("Cubchoo", "Petznief"), ("Beartic", "Siberio"),
    ("Cryogonal", "Frigometri"), ("Shelmet", "Schnuthelm"), ("Accelgor", "Hydragil"),
    ("Stunfisk", "Flunschlik"), ("Mienfoo", "Lin-Fu"), ("Mienshao", "Wie-Shu"),
    ("Druddigon", "Shardrago"), ("Golett", "Golbit"), ("Golurk", "Golgantes"),
    ("Pawniard", "Gladiantri"), ("Bisharp", "Caesurio"),
    ("Bouffalant", "Bisofank"), ("Rufflet", "Geronimatz"), ("Braviary", "Washakwil"),
    ("Vullaby", "Skallyk"), ("Mandibuzz", "Grypheldis"),
    ("Heatmor", "Furnifraß"), ("Durant", "Fermicula"),
    ("Deino", "Kapuno"), ("Zweilous", "Duodino"), ("Hydreigon", "Trikephalo"),
    ("Larvesta", "Ignivor"), ("Volcarona", "Ramoth"),
    ("Cobalion", "Kobalium"), ("Terrakion", "Terrakium"), ("Virizion", "Viridium"),
    ("Tornadus", "Boreos"), ("Thundurus", "Voltolos"), ("Landorus", "Demeteros"),
    ("Reshiram", "Reshiram"), ("Zekrom", "Zekrom"), ("Kyurem", "Kyurem"),
    ("Keldeo", "Keldeo"), ("Meloetta", "Meloetta"), ("Genesect", "Genesect"),
    # Gen 6 (650-721)
    ("Chespin", "Igamaro"), ("Quilladin", "Igastarnish"), ("Chesnaught", "Brigaron"),
    ("Fennekin", "Fynx"), ("Braixen", "Rutena"), ("Delphox", "Fennexis"),
    ("Froakie", "Froxy"), ("Frogadier", "Amphizel"), ("Greninja", "Quajutsu"),
    ("Bunnelby", "Scoppel"), ("Diggersby", "Grebbit"),
    ("Fletchling", "Dartiri"), ("Fletchinder", "Dartignis"), ("Talonflame", "Fiaro"),
    ("Scatterbug", "Purmel"), ("Spewpa", "Puponcho"), ("Vivillon", "Vivillon"),
    ("Litleo", "Leufeo"), ("Pyroar", "Pyroleo"),
    ("Flabebe", "Flabebe"), ("Floette", "Floette"), ("Florges", "Florges"),
    ("Skiddo", "Mekeras"), ("Gogoat", "Chevrumm"),
    ("Pancham", "Pam-Pam"), ("Pangoro", "Pandagro"),
    ("Furfrou", "Coiffwaff"), ("Espurr", "Psiau"), ("Meowstic", "Psiaugon"),
    ("Honedge", "Gramokles"), ("Doublade", "Duokles"), ("Aegislash", "Durengard"),
    ("Spritzee", "Parfi"), ("Aromatisse", "Parfini"),
    ("Swirlix", "Flauschling"), ("Slurpuff", "Sabbaione"),
    ("Inkay", "Iscalar"), ("Malamar", "Calamanero"),
    ("Binacle", "Bithora"), ("Barbaracle", "Thanathora"),
    ("Skrelp", "Algitt"), ("Dragalge", "Tandrak"),
    ("Clauncher", "Scampisto"), ("Clawitzer", "Wummer"),
    ("Helioptile", "Eguana"), ("Heliolisk", "Elezard"),
    ("Tyrunt", "Balgoras"), ("Tyrantrum", "Monargoras"),
    ("Amaura", "Amarino"), ("Aurorus", "Amagarga"),
    ("Sylveon", "Feelinara"), ("Hawlucha", "Resladero"),
    ("Dedenne", "Dedenne"), ("Carbink", "Rocara"),
    ("Goomy", "Viscora"), ("Sliggoo", "Viscargot"), ("Goodra", "Viscogon"),
    ("Klefki", "Clavion"), ("Phantump", "Paragoni"), ("Trevenant", "Trombork"),
    ("Pumpkaboo", "Irrbis"), ("Gourgeist", "Pumpdjinn"),
    ("Bergmite", "Arktip"), ("Avalugg", "Arktilas"),
    ("Noibat", "eF-eM"), ("Noivern", "UHaFnir"),
    ("Xerneas", "Xerneas"), ("Yveltal", "Yveltal"), ("Zygarde", "Zygarde"),
    ("Diancie", "Diancie"), ("Hoopa", "Hoopa"), ("Volcanion", "Volcanion"),
]

# Build lookup dicts
ENGLISH_NAMES = [e for e, g in POKEMON_ALL]
GERMAN_NAMES = [g for e, g in POKEMON_ALL]
ALL_NAMES = list(set(ENGLISH_NAMES + GERMAN_NAMES))

# Mapping: any name (EN or DE, lowercase) -> English name
NAME_TO_ENGLISH = {}
for en, de in POKEMON_ALL:
    NAME_TO_ENGLISH[en.lower()] = en
    NAME_TO_ENGLISH[de.lower()] = en
    # Also clean versions
    import re
    NAME_TO_ENGLISH[re.sub(r'[^a-z]', '', en.lower())] = en
    NAME_TO_ENGLISH[re.sub(r'[^a-z]', '', de.lower())] = en
